service: check-inventory-step-function
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

plugins: 
  - serverless-step-functions
  - serverless-iam-roles-per-function

stepFunctions:
  stateMachines:
    storeCheckoutFlow:
      name: storeCheckoutFlow
      definition:
        StartAt: checkInventory
        States: 
          
          checkInventory:
            Type: Task
            Resource: {"Fn::GetAtt": ["checkInventory", "Arn"]}
            Catch: 
              - ErrorEquals: [BookNotFound]
                Next: BookNotFoundError
              - ErrorEquals: [BookOutOfStock]
                Next: BookOutOfStockError
            ResultPath: "$.book"          #The entire input object is represented by $. We are adding a new attribute called "book"
            Next: calculateTotal

          calculateTotal: 
            Type: Task
            Resource: {"Fn::GetAtt": ["calculateTotal", "Arn"]}
            End: true
            ResultPath: "$.total"        #The entire input object is represented by $. We are adding a new attribute called "book"
          
          isReedemNeeded: 
            Type: Choice
            Choices: 
              - Variable: $.reedem
                BooleanEquals: true
                Next: ReedemPoints
            Default: BillCustomer

          RedeemPoints: 
            Type: Task
            Resource: {"Fn::GetAtt": ["redeemPoints", "Arn"]}
            Next: BillCustomer

          BillCustomer: 
            Type: Task
            Resource: {"Fn::GetAtt": ["billCustomer", "Arn"]}
            Next: PreparOrder

          
          BookNotFoundError:
            Type: Pass
            Result: "No such book avaialable"
            End: true

          BookOutOfStockError:
            Type: Pass
            Result: "Sorry, the book is out of stock"
            End: true
          
functions:
  checkInventory:
    handler: functions/checkInventory.handler
    iamRoleStatements:
      - Effect: Allow
        Resource: {"Fn::GetAtt": ["BooksTable", "Arn"]}
        Action: "dynmodb:*"

  calculateTotal:
    handler: functions/calculateTotal.handler

  redeemPoints:
    handler: functions/redeemPoints.handler

  billCustomer:
    handler: functions/billCustomer.handler


# you can add CloudFormation resource templates here
resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookTable
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST

      
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
